In [17]:
import pandas as pd
import pandas as pd

In [5]:
lst = ['ks', 'as', 'ds', 'ss']
s  = pd.Series(lst)
print(s)

0    ks
1    as
2    ds
3    ss
dtype: object

In [12]:
d = {
    "rollNo": [6, 11,19, 21],
    "name" : ['ks', 'as', 'ds', 'ss'],
    "marks" : [90,70,80,60],
    "branch": ["CS","EC" ,"arch", "PC"]
}

print(d)
print(type(d))

df = pd.DataFrame(d, index = ['a', 'b', 'c', 'd'])
print(df)

{'rollNo': [6, 11, 19, 21], 'name': ['ks', 'as', 'ds', 'ss'], 'marks': [90, 70, 80, 60], 'branch': ['CS', 'EC', 'arch', 'PC']}
<class 'dict'>
   rollNo name  marks branch
a       6   ks     90     CS
b      11   as     70     EC
c      19   ds     80   arch
d      21   ss     60     PC

In [11]:
lst = ['ks', 'as', 'ds', 'ss']
s  = pd.Series(lst, index = ['a', 'b', 'c', 'd'])
print(s)

a    ks
b    as
c    ds
d    ss
dtype: object

In [4]:
df = pd.read_csv("student.csv")
print(df)

             name                class                  subject  marks  gender
0    Rohan Sharma  B.Tech CSE 3rd Year      Database Management     69    Male
1     Rohan Kumar  B.Tech CSE 1st Year          Cloud Computing     82    Male
2    Khushi Verma  B.Tech CSE 2nd Year      Database Management     87    Male
3     Karan Gupta  B.Tech CSE 4th Year      Database Management     83  Female
4    Khushi Singh  B.Tech CSE 4th Year        Computer Networks     72    Male
5      Diya Patel  B.Tech CSE 1st Year               Algorithms     79    Male
6     Rahul Patel  B.Tech CSE 3rd Year          Data Structures     84    Male
7    Simran Verma  B.Tech CSE 3rd Year     Software Engineering     94  Female
8     Aditi Gupta  B.Tech CSE 1st Year          Data Structures     97    Male
9    Aditya Verma  B.Tech CSE 2nd Year               Algorithms     79  Female
10    Nisha Patel  B.Tech CSE 2nd Year        Computer Networks     77    Male
11     Isha Verma  B.Tech CSE 2nd Year          Web Development     70    Male
12     Nisha Jain  B.Tech CSE 3rd Year     Software Engineering     99    Male
13    Neha Sharma  B.Tech CSE 2nd Year          Data Structures     75  Female
14     Isha Verma  B.Tech CSE 2nd Year          Cloud Computing    100  Female
15    Diya Mishra  B.Tech CSE 4th Year     Software Engineering     84    Male
16     Isha Singh  B.Tech CSE 2nd Year     Discrete Mathematics     90  Female
17     Aditi Jain  B.Tech CSE 4th Year        Computer Networks     69    Male
18   Meera Mishra  B.Tech CSE 1st Year          Data Structures     62    Male
19     Arjun Jain  B.Tech CSE 1st Year         Machine Learning     79  Female
20    Meera Yadav  B.Tech CSE 1st Year     Software Engineering     62  Female
21     Neha Verma  B.Tech CSE 3rd Year         Machine Learning     65  Female
22   Khushi Yadav  B.Tech CSE 2nd Year          Web Development     61  Female
23      Meera Roy  B.Tech CSE 2nd Year       Python Programming     78    Male
24    Karan Kumar  B.Tech CSE 1st Year          Cloud Computing     75  Female
25   Khushi Verma  B.Tech CSE 3rd Year        Operating Systems     70    Male
26      Kabir Roy  B.Tech CSE 1st Year               Algorithms     86    Male
27    Karan Singh  B.Tech CSE 2nd Year     Software Engineering     85    Male
28     Isha Kumar  B.Tech CSE 4th Year      Database Management     89    Male
29    Aditya Jain  B.Tech CSE 3rd Year  Artificial Intelligence     88  Female
30    Rohan Gupta  B.Tech CSE 2nd Year               Algorithms     76    Male
31    Aditi Kumar  B.Tech CSE 2nd Year          Cloud Computing     69    Male
32  Ananya Sharma  B.Tech CSE 2nd Year               Algorithms     57  Female
33   Ananya Kumar  B.Tech CSE 2nd Year        Operating Systems     97  Female
34     Diya Kumar  B.Tech CSE 2nd Year     Discrete Mathematics     91  Female
35   Kabir Mishra  B.Tech CSE 4th Year      Database Management     61    Male
36     Yash Patel  B.Tech CSE 4th Year         Machine Learning     84    Male
37   Rohan Sharma  B.Tech CSE 4th Year     Discrete Mathematics     76    Male
38    Kabir Gupta  B.Tech CSE 2nd Year          Web Development     83    Male
39     Yash Singh  B.Tech CSE 3rd Year  Artificial Intelligence     70    Male
40    Nisha Kumar  B.Tech CSE 1st Year          Data Structures     96    Male
41   Ananya Gupta  B.Tech CSE 2nd Year         Machine Learning     86  Female
42      Diya Jain  B.Tech CSE 1st Year       Python Programming     79    Male
43   Simran Yadav  B.Tech CSE 4th Year        Operating Systems     82  Female
44    Priya Gupta  B.Tech CSE 3rd Year      Database Management     58    Male
45    Neha Sharma  B.Tech CSE 1st Year          Cloud Computing     85    Male
46    Aarav Kumar  B.Tech CSE 1st Year       Python Programming     59    Male
47     Kabir Jain  B.Tech CSE 1st Year          Cloud Computing     70    Male
48   Ritika Verma  B.Tech CSE 4th Year     Software Engineering     92  Female
49     Isha Gupta  B.Tech CSE 3rd Year      Database Management     71  Female
50    Priya Yadav  B.Tech CSE 4th Year        Computer Networks     59    Male
51      Nisha Roy  B.Tech CSE 1st Year               Algorithms     89    Male
52    Meera Yadav  B.Tech CSE 2nd Year        Computer Networks     59    Male
53    Rahul Yadav  B.Tech CSE 2nd Year  Artificial Intelligence     89  Female
54   Ritika Kumar  B.Tech CSE 1st Year     Software Engineering     90  Female
55    Rohan Singh  B.Tech CSE 3rd Year               Algorithms     61    Male
56     Isha Yadav  B.Tech CSE 2nd Year     Discrete Mathematics     76    Male
57     Isha Kumar  B.Tech CSE 4th Year        Operating Systems     58    Male
58     Yash Yadav  B.Tech CSE 1st Year          Data Structures     76    Male
59     Isha Singh  B.Tech CSE 4th Year          Web Development    100  Female

In [5]:
df.head()

           name                class              subject  marks  gender
0  Rohan Sharma  B.Tech CSE 3rd Year  Database Management     69    Male
1   Rohan Kumar  B.Tech CSE 1st Year      Cloud Computing     82    Male
2  Khushi Verma  B.Tech CSE 2nd Year  Database Management     87    Male
3   Karan Gupta  B.Tech CSE 4th Year  Database Management     83  Female
4  Khushi Singh  B.Tech CSE 4th Year    Computer Networks     72    Male

In [6]:
df.tail()

           name                class               subject  marks  gender
55  Rohan Singh  B.Tech CSE 3rd Year            Algorithms     61    Male
56   Isha Yadav  B.Tech CSE 2nd Year  Discrete Mathematics     76    Male
57   Isha Kumar  B.Tech CSE 4th Year     Operating Systems     58    Male
58   Yash Yadav  B.Tech CSE 1st Year       Data Structures     76    Male
59   Isha Singh  B.Tech CSE 4th Year       Web Development    100  Female

In [10]:
##print(df["subject"])
print(df["subject"].head())

0    Database Management
1        Cloud Computing
2    Database Management
3    Database Management
4      Computer Networks
Name: subject, dtype: object

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     60 non-null     object
 1   class    60 non-null     object
 2   subject  60 non-null     object
 3   marks    60 non-null     int64
 4   gender   60 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.5+ KB

In [12]:
df.describe()

            marks
count   60.000000
mean    78.150000
std     12.225044
min     57.000000
25%     69.750000
50%     79.000000
75%     87.250000
max    100.000000

In [14]:
df.shape

(60, 5)

In [15]:
df[["name", "class"]]

             name                class
0    Rohan Sharma  B.Tech CSE 3rd Year
1     Rohan Kumar  B.Tech CSE 1st Year
2    Khushi Verma  B.Tech CSE 2nd Year
3     Karan Gupta  B.Tech CSE 4th Year
4    Khushi Singh  B.Tech CSE 4th Year
5      Diya Patel  B.Tech CSE 1st Year
6     Rahul Patel  B.Tech CSE 3rd Year
7    Simran Verma  B.Tech CSE 3rd Year
8     Aditi Gupta  B.Tech CSE 1st Year
9    Aditya Verma  B.Tech CSE 2nd Year
10    Nisha Patel  B.Tech CSE 2nd Year
11     Isha Verma  B.Tech CSE 2nd Year
12     Nisha Jain  B.Tech CSE 3rd Year
13    Neha Sharma  B.Tech CSE 2nd Year
14     Isha Verma  B.Tech CSE 2nd Year
15    Diya Mishra  B.Tech CSE 4th Year
16     Isha Singh  B.Tech CSE 2nd Year
17     Aditi Jain  B.Tech CSE 4th Year
18   Meera Mishra  B.Tech CSE 1st Year
19     Arjun Jain  B.Tech CSE 1st Year
20    Meera Yadav  B.Tech CSE 1st Year
21     Neha Verma  B.Tech CSE 3rd Year
22   Khushi Yadav  B.Tech CSE 2nd Year
23      Meera Roy  B.Tech CSE 2nd Year
24    Karan Kumar  B.Tech CSE 1st Year
25   Khushi Verma  B.Tech CSE 3rd Year
26      Kabir Roy  B.Tech CSE 1st Year
27    Karan Singh  B.Tech CSE 2nd Year
28     Isha Kumar  B.Tech CSE 4th Year
29    Aditya Jain  B.Tech CSE 3rd Year
30    Rohan Gupta  B.Tech CSE 2nd Year
31    Aditi Kumar  B.Tech CSE 2nd Year
32  Ananya Sharma  B.Tech CSE 2nd Year
33   Ananya Kumar  B.Tech CSE 2nd Year
34     Diya Kumar  B.Tech CSE 2nd Year
35   Kabir Mishra  B.Tech CSE 4th Year
36     Yash Patel  B.Tech CSE 4th Year
37   Rohan Sharma  B.Tech CSE 4th Year
38    Kabir Gupta  B.Tech CSE 2nd Year
39     Yash Singh  B.Tech CSE 3rd Year
40    Nisha Kumar  B.Tech CSE 1st Year
41   Ananya Gupta  B.Tech CSE 2nd Year
42      Diya Jain  B.Tech CSE 1st Year
43   Simran Yadav  B.Tech CSE 4th Year
44    Priya Gupta  B.Tech CSE 3rd Year
45    Neha Sharma  B.Tech CSE 1st Year
46    Aarav Kumar  B.Tech CSE 1st Year
47     Kabir Jain  B.Tech CSE 1st Year
48   Ritika Verma  B.Tech CSE 4th Year
49     Isha Gupta  B.Tech CSE 3rd Year
50    Priya Yadav  B.Tech CSE 4th Year
51      Nisha Roy  B.Tech CSE 1st Year
52    Meera Yadav  B.Tech CSE 2nd Year
53    Rahul Yadav  B.Tech CSE 2nd Year
54   Ritika Kumar  B.Tech CSE 1st Year
55    Rohan Singh  B.Tech CSE 3rd Year
56     Isha Yadav  B.Tech CSE 2nd Year
57     Isha Kumar  B.Tech CSE 4th Year
58     Yash Yadav  B.Tech CSE 1st Year
59     Isha Singh  B.Tech CSE 4th Year

In [18]:
print(df.loc[0])

name              Rohan Sharma
class      B.Tech CSE 3rd Year
subject    Database Management
marks                       69
gender                    Male
Name: 0, dtype: object

In [32]:
print(df[(df["marks"] > 80) & (df["class"] == "B.Tech CSE 1st Year")])

            name                class               subject  marks  gender
1    Rohan Kumar  B.Tech CSE 1st Year       Cloud Computing     82    Male
8    Aditi Gupta  B.Tech CSE 1st Year       Data Structures     97    Male
26     Kabir Roy  B.Tech CSE 1st Year            Algorithms     86    Male
40   Nisha Kumar  B.Tech CSE 1st Year       Data Structures     96    Male
45   Neha Sharma  B.Tech CSE 1st Year       Cloud Computing     85    Male
51     Nisha Roy  B.Tech CSE 1st Year            Algorithms     89    Male
54  Ritika Kumar  B.Tech CSE 1st Year  Software Engineering     90  Female

In [36]:
##TASK

std = pd.read_csv("student_dataset.csv")
std

   RollNo   Name  Age    City  Marks
0     101   Amit   20   Delhi     85
1     102  Priya   21  Mumbai     90
2     103  Rahul   19    Pune     78
3     104  Sneha   22   Delhi     88
4     105  Karan   20  Jaipur     76

In [37]:
std.head(3)

   RollNo   Name  Age    City  Marks
0     101   Amit   20   Delhi     85
1     102  Priya   21  Mumbai     90
2     103  Rahul   19    Pune     78

In [38]:
std.tail(2)

   RollNo   Name  Age    City  Marks
3     104  Sneha   22   Delhi     88
4     105  Karan   20  Jaipur     76

In [40]:
std["Name"]

0     Amit
1    Priya
2    Rahul
3    Sneha
4    Karan
Name: Name, dtype: object

In [43]:
std[["Name", "Marks"]]

    Name  Marks
0   Amit     85
1  Priya     90
2  Rahul     78
3  Sneha     88
4  Karan     76

In [44]:
std.shape

(5, 5)

In [46]:
std.columns

Index(['RollNo', 'Name', 'Age', 'City', 'Marks'], dtype='object')

In [47]:
std.describe()

           RollNo        Age     Marks
count    5.000000   5.000000   5.00000
mean   103.000000  20.400000  83.40000
std      1.581139   1.140175   6.14817
min    101.000000  19.000000  76.00000
25%    102.000000  20.000000  78.00000
50%    103.000000  20.000000  85.00000
75%    104.000000  21.000000  88.00000
max    105.000000  22.000000  90.00000

In [126]:
import pandas as pd

df = pd.DataFrame({
    "ID": range(1, 21),
    "Name": ["Aarna","Vamika","Samaira","Anvika","Ahaana", "","Kashvi","Inaya","Mahika","Tvesa",
 "Prisha","Navya","Mysha","Ruhani","Ziana","Avyanna","Yuvika","Anvitha","Vihana","Kiddo"],
    "Age": [19,20,21,22,20,23,21,22,19,20,21,22,23,20,19,21,22,20,21,23],
    "City": ["Lucknow","Delhi","Mumbai","Pune","Kanpur","Noida","Agra","Jaipur","Delhi","Mumbai",
             "Pune","Lucknow","Kanpur","Noida","Agra","Jaipur","Delhi","Mumbai","Pune","Lucknow"],
    "Marks": [85,90,78,88,92,76,81,95,89,84,73,77,80,91,87,79,83,86,90,88],
    "Department": ["CS","IT","CS","IT","EC","CS","IT","EC","CS","IT",
                   "EC","CS","IT","EC","CS","IT","EC","CS","IT","EC"],
    "Salary": [30000,32000,28000,35000,40000,27000,33000,42000,31000,34000,
               29000,30000,36000,41000,30500,32500,38000,31500,34500,39500]
})
#print(df)
df.to_csv("studentInfo.csv", index = False)
df = pd.read_csv("studentInfo.csv")
print(df)

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarna   19  Lucknow     85         CS   30000
1    2   Vamika   20    Delhi     90         IT   32000
2    3  Samaira   21   Mumbai     78         CS   28000
3    4   Anvika   22     Pune     88         IT   35000
4    5   Ahaana   20   Kanpur     92         EC   40000
5    6      NaN   23    Noida     76         CS   27000
6    7   Kashvi   21     Agra     81         IT   33000
7    8    Inaya   22   Jaipur     95         EC   42000
8    9   Mahika   19    Delhi     89         CS   31000
9   10    Tvesa   20   Mumbai     84         IT   34000
10  11   Prisha   21     Pune     73         EC   29000
11  12    Navya   22  Lucknow     77         CS   30000
12  13    Mysha   23   Kanpur     80         IT   36000
13  14   Ruhani   20    Noida     91         EC   41000
14  15    Ziana   19     Agra     87         CS   30500
15  16  Avyanna   21   Jaipur     79         IT   32500
16  17   Yuvika   22    Delhi     83         EC   38000
17  18  Anvitha   20   Mumbai     86         CS   31500
18  19   Vihana   21     Pune     90         IT   34500
19  20    Kiddo   23  Lucknow     88         EC   39500

In [60]:
df.head()

   ID     Name  Age     City  Marks Department  Salary
0   1    Aarna   19  Lucknow     85         CS   30000
1   2   Vamika   20    Delhi     90         IT   32000
2   3  Samaira   21   Mumbai     78         CS   28000
3   4   Anvika   22     Pune     88         IT   35000
4   5     Nyra   20   Kanpur     92         EC   40000

In [61]:
df.tail()

    ID     Name  Age     City  Marks Department  Salary
15  16  Avyanna   21   Jaipur     79         IT   32500
16  17   Yuvika   22    Delhi     83         EC   38000
17  18  Anvitha   20   Mumbai     86         CS   31500
18  19   Vihana   21     Pune     90         IT   34500
19  20    Kiddo   23  Lucknow     88         EC   39500

In [62]:
#Returns random rows from the DataFrame. 
df.sample()

   ID    Name  Age  City  Marks Department  Salary
6   7  Kashvi   21  Agra     81         IT   33000

In [63]:
df.shape

(20, 7)

In [64]:
df.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks', 'Department', 'Salary'], dtype='object')

In [65]:
#df.index[3]
df.index

RangeIndex(start=0, stop=20, step=1)

In [66]:
df.dtypes

ID             int64
Name          object
Age            int64
City          object
Marks          int64
Department    object
Salary         int64
dtype: object

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          20 non-null     int64
 1   Name        20 non-null     object
 2   Age         20 non-null     int64
 3   City        20 non-null     object
 4   Marks       20 non-null     int64
 5   Department  20 non-null     object
 6   Salary      20 non-null     int64
dtypes: int64(4), object(3)
memory usage: 1.2+ KB

In [68]:
df.describe()

             ID        Age      Marks       Salary
count  20.00000  20.000000  20.000000     20.00000
mean   10.50000  20.950000  84.600000  33725.00000
std     5.91608   1.316894   6.029751   4446.98301
min     1.00000  19.000000  73.000000  27000.00000
25%     5.75000  20.000000  79.750000  30375.00000
50%    10.50000  21.000000  85.500000  32750.00000
75%    15.25000  22.000000  89.250000  36500.00000
max    20.00000  23.000000  95.000000  42000.00000

In [69]:
df["Name"]

0       Aarna
1      Vamika
2     Samaira
3      Anvika
4        Nyra
5      Ahaana
6      Kashvi
7       Inaya
8      Mahika
9       Tvesa
10     Prisha
11      Navya
12      Mysha
13     Ruhani
14      Ziana
15    Avyanna
16     Yuvika
17    Anvitha
18     Vihana
19      Kiddo
Name: Name, dtype: object

In [70]:
df.loc[2, 'Name']

'Samaira'

In [71]:
df.iloc[1, 5]

'IT'

In [74]:
df.sort_values("Salary")

    ID     Name  Age     City  Marks Department  Salary
5    6   Ahaana   23    Noida     76         CS   27000
2    3  Samaira   21   Mumbai     78         CS   28000
10  11   Prisha   21     Pune     73         EC   29000
0    1    Aarna   19  Lucknow     85         CS   30000
11  12    Navya   22  Lucknow     77         CS   30000
14  15    Ziana   19     Agra     87         CS   30500
8    9   Mahika   19    Delhi     89         CS   31000
17  18  Anvitha   20   Mumbai     86         CS   31500
1    2   Vamika   20    Delhi     90         IT   32000
15  16  Avyanna   21   Jaipur     79         IT   32500
6    7   Kashvi   21     Agra     81         IT   33000
9   10    Tvesa   20   Mumbai     84         IT   34000
18  19   Vihana   21     Pune     90         IT   34500
3    4   Anvika   22     Pune     88         IT   35000
12  13    Mysha   23   Kanpur     80         IT   36000
16  17   Yuvika   22    Delhi     83         EC   38000
19  20    Kiddo   23  Lucknow     88         EC   39500
4    5     Nyra   20   Kanpur     92         EC   40000
13  14   Ruhani   20    Noida     91         EC   41000
7    8    Inaya   22   Jaipur     95         EC   42000

In [78]:
df.sort_index(ascending = False)

    ID     Name  Age     City  Marks Department  Salary
19  20    Kiddo   23  Lucknow     88         EC   39500
18  19   Vihana   21     Pune     90         IT   34500
17  18  Anvitha   20   Mumbai     86         CS   31500
16  17   Yuvika   22    Delhi     83         EC   38000
15  16  Avyanna   21   Jaipur     79         IT   32500
14  15    Ziana   19     Agra     87         CS   30500
13  14   Ruhani   20    Noida     91         EC   41000
12  13    Mysha   23   Kanpur     80         IT   36000
11  12    Navya   22  Lucknow     77         CS   30000
10  11   Prisha   21     Pune     73         EC   29000
9   10    Tvesa   20   Mumbai     84         IT   34000
8    9   Mahika   19    Delhi     89         CS   31000
7    8    Inaya   22   Jaipur     95         EC   42000
6    7   Kashvi   21     Agra     81         IT   33000
5    6   Ahaana   23    Noida     76         CS   27000
4    5     Nyra   20   Kanpur     92         EC   40000
3    4   Anvika   22     Pune     88         IT   35000
2    3  Samaira   21   Mumbai     78         CS   28000
1    2   Vamika   20    Delhi     90         IT   32000
0    1    Aarna   19  Lucknow     85         CS   30000

In [85]:
df.isna()

       ID   Name    Age   City  Marks  Department  Salary
0   False  False  False  False  False       False   False
1   False  False  False  False  False       False   False
2   False  False  False  False  False       False   False
3   False  False  False  False  False       False   False
4   False  False  False  False  False       False   False
5   False   True  False  False  False       False   False
6   False  False  False  False  False       False   False
7   False  False  False  False  False       False   False
8   False  False  False  False  False       False   False
9   False  False  False  False  False       False   False
10  False  False  False  False  False       False   False
11  False  False  False  False  False       False   False
12  False  False  False  False  False       False   False
13  False  False  False  False  False       False   False
14  False  False  False  False  False       False   False
15  False  False  False  False  False       False   False
16  False  False  False  False  False       False   False
17  False  False  False  False  False       False   False
18  False  False  False  False  False       False   False
19  False  False  False  False  False       False   False

In [88]:
df.notnull()

      ID   Name   Age  City  Marks  Department  Salary
0   True   True  True  True   True        True    True
1   True   True  True  True   True        True    True
2   True   True  True  True   True        True    True
3   True   True  True  True   True        True    True
4   True   True  True  True   True        True    True
5   True  False  True  True   True        True    True
6   True   True  True  True   True        True    True
7   True   True  True  True   True        True    True
8   True   True  True  True   True        True    True
9   True   True  True  True   True        True    True
10  True   True  True  True   True        True    True
11  True   True  True  True   True        True    True
12  True   True  True  True   True        True    True
13  True   True  True  True   True        True    True
14  True   True  True  True   True        True    True
15  True   True  True  True   True        True    True
16  True   True  True  True   True        True    True
17  True   True  True  True   True        True    True
18  True   True  True  True   True        True    True
19  True   True  True  True   True        True    True

In [90]:
#df.dropna()

In [100]:
df.fillna("mikasa")

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarna   19  Lucknow     85         CS   30000
1    2   Vamika   20    Delhi     90         IT   32000
2    3  Samaira   21   Mumbai     78         CS   28000
3    4   Anvika   22     Pune     88         IT   35000
4    5   Ahaana   20   Kanpur     92         EC   40000
5    6   mikasa   23    Noida     76         CS   27000
6    7   Kashvi   21     Agra     81         IT   33000
7    8    Inaya   22   Jaipur     95         EC   42000
8    9   Mahika   19    Delhi     89         CS   31000
9   10    Tvesa   20   Mumbai     84         IT   34000
10  11   Prisha   21     Pune     73         EC   29000
11  12    Navya   22  Lucknow     77         CS   30000
12  13    Mysha   23   Kanpur     80         IT   36000
13  14   Ruhani   20    Noida     91         EC   41000
14  15    Ziana   19     Agra     87         CS   30500
15  16  Avyanna   21   Jaipur     79         IT   32500
16  17   Yuvika   22    Delhi     83         EC   38000
17  18  Anvitha   20   Mumbai     86         CS   31500
18  19   Vihana   21     Pune     90         IT   34500
19  20    Kiddo   23  Lucknow     88         EC   39500

In [107]:
print(df.replace('Kanpur','sadie'))

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarna   19  Lucknow     85         CS   30000
1    2   Vamika   20    Delhi     90         IT   32000
2    3  Samaira   21   Mumbai     78         CS   28000
3    4   Anvika   22     Pune     88         IT   35000
4    5   Ahaana   20    sadie     92         EC   40000
5    6      NaN   23    Noida     76         CS   27000
6    7   Kashvi   21     Agra     81         IT   33000
7    8    Inaya   22   Jaipur     95         EC   42000
8    9   Mahika   19    Delhi     89         CS   31000
9   10    Tvesa   20   Mumbai     84         IT   34000
10  11   Prisha   21     Pune     73         EC   29000
11  12    Navya   22  Lucknow     77         CS   30000
12  13    Mysha   23    sadie     80         IT   36000
13  14   Ruhani   20    Noida     91         EC   41000
14  15    Ziana   19     Agra     87         CS   30500
15  16  Avyanna   21   Jaipur     79         IT   32500
16  17   Yuvika   22    Delhi     83         EC   38000
17  18  Anvitha   20   Mumbai     86         CS   31500
18  19   Vihana   21     Pune     90         IT   34500
19  20    Kiddo   23  Lucknow     88         EC   39500

In [106]:
df

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarna   19  Lucknow     85         CS   30000
1    2   Vamika   20    Delhi     90         IT   32000
2    3  Samaira   21   Mumbai     78         CS   28000
3    4   Anvika   22     Pune     88         IT   35000
4    5   Ahaana   20   Kanpur     92         EC   40000
5    6      NaN   23    Noida     76         CS   27000
6    7   Kashvi   21     Agra     81         IT   33000
7    8    Inaya   22   Jaipur     95         EC   42000
8    9   Mahika   19    Delhi     89         CS   31000
9   10    Tvesa   20   Mumbai     84         IT   34000
10  11   Prisha   21     Pune     73         EC   29000
11  12    Navya   22  Lucknow     77         CS   30000
12  13    Mysha   23   Kanpur     80         IT   36000
13  14   Ruhani   20    Noida     91         EC   41000
14  15    Ziana   19     Agra     87         CS   30500
15  16  Avyanna   21   Jaipur     79         IT   32500
16  17   Yuvika   22    Delhi     83         EC   38000
17  18  Anvitha   20   Mumbai     86         CS   31500
18  19   Vihana   21     Pune     90         IT   34500
19  20    Kiddo   23  Lucknow     88         EC   39500

In [ ]:
print(df.dropna(inplace=True)) #it removes null values from the file permanently

In [121]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame({
    "Student_ID": [101,102,103,104,105,106,107,108,109,110,
                   111,112,113,114,115,116,117,118,119,120],

    "Name": ["Aman","Riya",None,"Karan","Priya","Rahul","Neha",None,
             "Vikas","Pooja","Ankit","Simran","Rohit",None,"Kajal",
             "Deepak","Meena","Arjun","Nisha",None],

    "Age": [20,21,np.nan,22,19,23,21,20,np.nan,22,
            24,23,21,20,22,np.nan,19,21,23,20],

    "City": ["Delhi","Mumbai","Pune",None,"Jaipur","Delhi","Mumbai",
             "Pune","Delhi",None,"Jaipur","Mumbai","Delhi","Pune",
             None,"Delhi","Mumbai","Jaipur","Pune","Delhi"],

    "Marks": [85,90,78,np.nan,88,76,91,82,95,np.nan,
              80,84,79,92,87,75,np.nan,89,81,93]
})

print(df1)

    Student_ID    Name   Age    City  Marks
0          101    Aman  20.0   Delhi   85.0
1          102    Riya  21.0  Mumbai   90.0
2          103    None   NaN    Pune   78.0
3          104   Karan  22.0    None    NaN
4          105   Priya  19.0  Jaipur   88.0
5          106   Rahul  23.0   Delhi   76.0
6          107    Neha  21.0  Mumbai   91.0
7          108    None  20.0    Pune   82.0
8          109   Vikas   NaN   Delhi   95.0
9          110   Pooja  22.0    None    NaN
10         111   Ankit  24.0  Jaipur   80.0
11         112  Simran  23.0  Mumbai   84.0
12         113   Rohit  21.0   Delhi   79.0
13         114    None  20.0    Pune   92.0
14         115   Kajal  22.0    None   87.0
15         116  Deepak   NaN   Delhi   75.0
16         117   Meena  19.0  Mumbai    NaN
17         118   Arjun  21.0  Jaipur   89.0
18         119   Nisha  23.0    Pune   81.0
19         120    None  20.0   Delhi   93.0

In [122]:
df1.fillna({"Marks":df["Marks"].mean()},inplace=True)

In [123]:
df1

    Student_ID    Name   Age    City  Marks
0          101    Aman  20.0   Delhi   85.0
1          102    Riya  21.0  Mumbai   90.0
2          103    None   NaN    Pune   78.0
3          104   Karan  22.0    None   85.0
4          105   Priya  19.0  Jaipur   88.0
5          106   Rahul  23.0   Delhi   76.0
6          107    Neha  21.0  Mumbai   91.0
7          108    None  20.0    Pune   82.0
8          109   Vikas   NaN   Delhi   95.0
9          110   Pooja  22.0    None   85.0
10         111   Ankit  24.0  Jaipur   80.0
11         112  Simran  23.0  Mumbai   84.0
12         113   Rohit  21.0   Delhi   79.0
13         114    None  20.0    Pune   92.0
14         115   Kajal  22.0    None   87.0
15         116  Deepak   NaN   Delhi   75.0
16         117   Meena  19.0  Mumbai   85.0
17         118   Arjun  21.0  Jaipur   89.0
18         119   Nisha  23.0    Pune   81.0
19         120    None  20.0   Delhi   93.0

In [116]:
df[df["Marks"]>85]

    Student_ID   Name   Age    City  Marks
1          102   Riya  21.0  Mumbai   90.0
4          105  Priya  19.0  Jaipur   88.0
6          107   Neha  21.0  Mumbai   91.0
8          109  Vikas   NaN   Delhi   95.0
13         114   None  20.0    Pune   92.0
14         115  Kajal  22.0    None   87.0
17         118  Arjun  21.0  Jaipur   89.0
19         120   None  20.0   Delhi   93.0

In [117]:
df[df["Age"]>20]

    Student_ID    Name   Age    City  Marks
1          102    Riya  21.0  Mumbai   90.0
3          104   Karan  22.0    None   85.0
5          106   Rahul  23.0   Delhi   76.0
6          107    Neha  21.0  Mumbai   91.0
9          110   Pooja  22.0    None   85.0
10         111   Ankit  24.0  Jaipur   80.0
11         112  Simran  23.0  Mumbai   84.0
12         113   Rohit  21.0   Delhi   79.0
14         115   Kajal  22.0    None   87.0
17         118   Arjun  21.0  Jaipur   89.0
18         119   Nisha  23.0    Pune   81.0

In [124]:
df1[df1["City"] == "Delhi"]

    Student_ID    Name   Age   City  Marks
0          101    Aman  20.0  Delhi   85.0
5          106   Rahul  23.0  Delhi   76.0
8          109   Vikas   NaN  Delhi   95.0
12         113   Rohit  21.0  Delhi   79.0
15         116  Deepak   NaN  Delhi   75.0
19         120    None  20.0  Delhi   93.0

In [120]:
df1[df1["City"] == "Mumbai"]

    Student_ID    Name   Age    City  Marks
1          102    Riya  21.0  Mumbai   90.0
6          107    Neha  21.0  Mumbai   91.0
11         112  Simran  23.0  Mumbai   84.0
16         117   Meena  19.0  Mumbai   85.0

In [127]:
df[df["Salary"]> 35000]

    ID    Name  Age     City  Marks Department  Salary
4    5  Ahaana   20   Kanpur     92         EC   40000
7    8   Inaya   22   Jaipur     95         EC   42000
12  13   Mysha   23   Kanpur     80         IT   36000
13  14  Ruhani   20    Noida     91         EC   41000
16  17  Yuvika   22    Delhi     83         EC   38000
19  20   Kiddo   23  Lucknow     88         EC   39500

In [128]:
df[df["Marks"] <80]

    ID     Name  Age     City  Marks Department  Salary
2    3  Samaira   21   Mumbai     78         CS   28000
5    6      NaN   23    Noida     76         CS   27000
10  11   Prisha   21     Pune     73         EC   29000
11  12    Navya   22  Lucknow     77         CS   30000
15  16  Avyanna   21   Jaipur     79         IT   32500

In [130]:
df[df["Age"] >21]

    ID    Name  Age     City  Marks Department  Salary
3    4  Anvika   22     Pune     88         IT   35000
5    6     NaN   23    Noida     76         CS   27000
7    8   Inaya   22   Jaipur     95         EC   42000
11  12   Navya   22  Lucknow     77         CS   30000
12  13   Mysha   23   Kanpur     80         IT   36000
16  17  Yuvika   22    Delhi     83         EC   38000
19  20   Kiddo   23  Lucknow     88         EC   39500

In [131]:
df[df["Department"] == 'CS']

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarna   19  Lucknow     85         CS   30000
2    3  Samaira   21   Mumbai     78         CS   28000
5    6      NaN   23    Noida     76         CS   27000
8    9   Mahika   19    Delhi     89         CS   31000
11  12    Navya   22  Lucknow     77         CS   30000
14  15    Ziana   19     Agra     87         CS   30500
17  18  Anvitha   20   Mumbai     86         CS   31500

In [132]:
df[df["Department"] == 'IT']

    ID     Name  Age    City  Marks Department  Salary
1    2   Vamika   20   Delhi     90         IT   32000
3    4   Anvika   22    Pune     88         IT   35000
6    7   Kashvi   21    Agra     81         IT   33000
9   10    Tvesa   20  Mumbai     84         IT   34000
12  13    Mysha   23  Kanpur     80         IT   36000
15  16  Avyanna   21  Jaipur     79         IT   32500
18  19   Vihana   21    Pune     90         IT   34500

In [133]:
df[df["City"] == "Lucknow"]

    ID   Name  Age     City  Marks Department  Salary
0    1  Aarna   19  Lucknow     85         CS   30000
11  12  Navya   22  Lucknow     77         CS   30000
19  20  Kiddo   23  Lucknow     88         EC   39500

In [134]:
df[(df["Marks"]>80)&(df["Age"]<21)]

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarna   19  Lucknow     85         CS   30000
1    2   Vamika   20    Delhi     90         IT   32000
4    5   Ahaana   20   Kanpur     92         EC   40000
8    9   Mahika   19    Delhi     89         CS   31000
9   10    Tvesa   20   Mumbai     84         IT   34000
13  14   Ruhani   20    Noida     91         EC   41000
14  15    Ziana   19     Agra     87         CS   30500
17  18  Anvitha   20   Mumbai     86         CS   31500

In [136]:
df[(df["City"] == "Delhi")&(df["Marks"]>85)]

   ID    Name  Age   City  Marks Department  Salary
1   2  Vamika   20  Delhi     90         IT   32000
8   9  Mahika   19  Delhi     89         CS   31000

In [138]:
df[(df["City"] == "Mumbai")| (df["City"] ==  "Pune")]

    ID     Name  Age    City  Marks Department  Salary
2    3  Samaira   21  Mumbai     78         CS   28000
3    4   Anvika   22    Pune     88         IT   35000
9   10    Tvesa   20  Mumbai     84         IT   34000
10  11   Prisha   21    Pune     73         EC   29000
17  18  Anvitha   20  Mumbai     86         CS   31500
18  19   Vihana   21    Pune     90         IT   34500

In [139]:
df[(df["City"] != "Lucknow")]

    ID     Name  Age    City  Marks Department  Salary
1    2   Vamika   20   Delhi     90         IT   32000
2    3  Samaira   21  Mumbai     78         CS   28000
3    4   Anvika   22    Pune     88         IT   35000
4    5   Ahaana   20  Kanpur     92         EC   40000
5    6      NaN   23   Noida     76         CS   27000
6    7   Kashvi   21    Agra     81         IT   33000
7    8    Inaya   22  Jaipur     95         EC   42000
8    9   Mahika   19   Delhi     89         CS   31000
9   10    Tvesa   20  Mumbai     84         IT   34000
10  11   Prisha   21    Pune     73         EC   29000
12  13    Mysha   23  Kanpur     80         IT   36000
13  14   Ruhani   20   Noida     91         EC   41000
14  15    Ziana   19    Agra     87         CS   30500
15  16  Avyanna   21  Jaipur     79         IT   32500
16  17   Yuvika   22   Delhi     83         EC   38000
17  18  Anvitha   20  Mumbai     86         CS   31500
18  19   Vihana   21    Pune     90         IT   34500

In [140]:
df[(df["Marks"]>80) & (df["Marks"]<90)]

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarna   19  Lucknow     85         CS   30000
3    4   Anvika   22     Pune     88         IT   35000
6    7   Kashvi   21     Agra     81         IT   33000
8    9   Mahika   19    Delhi     89         CS   31000
9   10    Tvesa   20   Mumbai     84         IT   34000
14  15    Ziana   19     Agra     87         CS   30500
16  17   Yuvika   22    Delhi     83         EC   38000
17  18  Anvitha   20   Mumbai     86         CS   31500
19  20    Kiddo   23  Lucknow     88         EC   39500

In [141]:
df[(df["Department"] == 'CS') |(df["Department"] == 'EC')]

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarna   19  Lucknow     85         CS   30000
2    3  Samaira   21   Mumbai     78         CS   28000
4    5   Ahaana   20   Kanpur     92         EC   40000
5    6      NaN   23    Noida     76         CS   27000
7    8    Inaya   22   Jaipur     95         EC   42000
8    9   Mahika   19    Delhi     89         CS   31000
10  11   Prisha   21     Pune     73         EC   29000
11  12    Navya   22  Lucknow     77         CS   30000
13  14   Ruhani   20    Noida     91         EC   41000
14  15    Ziana   19     Agra     87         CS   30500
16  17   Yuvika   22    Delhi     83         EC   38000
17  18  Anvitha   20   Mumbai     86         CS   31500
19  20    Kiddo   23  Lucknow     88         EC   39500

In [143]:
df[(df["Salary"] > 32000) & (df["Department"] == 'IT')]

    ID     Name  Age    City  Marks Department  Salary
3    4   Anvika   22    Pune     88         IT   35000
6    7   Kashvi   21    Agra     81         IT   33000
9   10    Tvesa   20  Mumbai     84         IT   34000
12  13    Mysha   23  Kanpur     80         IT   36000
15  16  Avyanna   21  Jaipur     79         IT   32500
18  19   Vihana   21    Pune     90         IT   34500

In [144]:
df[(df["Age"] > 21) | (df["Marks"] > 90)]

    ID    Name  Age     City  Marks Department  Salary
3    4  Anvika   22     Pune     88         IT   35000
4    5  Ahaana   20   Kanpur     92         EC   40000
5    6     NaN   23    Noida     76         CS   27000
7    8   Inaya   22   Jaipur     95         EC   42000
11  12   Navya   22  Lucknow     77         CS   30000
12  13   Mysha   23   Kanpur     80         IT   36000
13  14  Ruhani   20    Noida     91         EC   41000
16  17  Yuvika   22    Delhi     83         EC   38000
19  20   Kiddo   23  Lucknow     88         EC   39500

In [145]:
df[(df["City"] == "Mumbai")| (df["City"] ==  "Mumbai") | (df["City"] == "Lucknow")]

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarna   19  Lucknow     85         CS   30000
2    3  Samaira   21   Mumbai     78         CS   28000
9   10    Tvesa   20   Mumbai     84         IT   34000
11  12    Navya   22  Lucknow     77         CS   30000
17  18  Anvitha   20   Mumbai     86         CS   31500
19  20    Kiddo   23  Lucknow     88         EC   39500

In [147]:
df[(df["Marks"] >85) & (df["Age"] >= 21)]

    ID    Name  Age     City  Marks Department  Salary
3    4  Anvika   22     Pune     88         IT   35000
7    8   Inaya   22   Jaipur     95         EC   42000
18  19  Vihana   21     Pune     90         IT   34500
19  20   Kiddo   23  Lucknow     88         EC   39500