In [75]:
import pandas as pd

df = pd.DataFrame({
    "Order_ID": [101,102,103,104,105,106,107,108,109,110,
                 111,112,113,114,115,116,117,118,119,120],

    "Order_DateTime": [
        "2025-01-05 09:15:30",
        "2025-01-12 14:45:20",
        "2025-02-03 11:20:10",
        "2025-02-18 16:35:45",
        "2025-03-07 10:05:25",
        "2025-03-25 18:50:40",
        "2025-04-10 08:30:15",
        "2025-04-22 13:40:55",
        "2025-05-05 17:10:35",
        "2025-05-28 12:25:50",
        "2025-06-11 15:45:05",
        "2025-06-30 19:20:30",
        "2025-07-04 09:55:15",
        "2025-07-19 11:15:40",
        "2025-08-08 14:05:25",
        "2025-08-26 16:50:10",
        "2025-09-09 10:40:20",
        "2025-10-14 18:30:45",
        "2025-11-21 13:15:35",
        "2025-12-30 20:10:50"
    ],

    "Customer": [
        "Rohit","Virat","Dhoni","Rahul","Hardik",
        "Gill","Ishan","Pant","Surya","Bumrah",
        "KL Rahul","Jadeja","Ashwin","Shami","Siraj",
        "Axar","Kuldeep","Arshdeep","Rinku","Tilak"
    ],

    "City": [
        "Delhi","Mumbai","Chennai","Lucknow","Pune",
        "Ahmedabad","Kolkata","Jaipur","Hyderabad","Delhi",
        "Mumbai","Chennai","Lucknow","Pune","Ahmedabad",
        "Kolkata","Hyderabad","Jaipur","Delhi","Mumbai"
    ],

    "Product": [
        "Laptop","Mobile","Tablet","Headphones","Keyboard",
        "Mouse","Monitor","Printer","Camera","Laptop",
        "Mobile","Tablet","Keyboard","Mouse","Monitor",
        "Printer","Camera","Laptop","Tablet","Mobile"
    ],

    "Sales": [
        65000,25000,18000,2500,1800,
        900,15000,12000,45000,70000,
        28000,20000,2200,1000,17000,
        14000,48000,72000,21000,30000
    ]
})

# Convert to DateTime
df["Order_DateTime"] = pd.to_datetime(sales_df["Order_DateTime"])

print(df)

    Order_ID      Order_DateTime  Customer       City     Product  Sales
0        101 2025-01-05 09:15:30     Rohit      Delhi      Laptop  65000
1        102 2025-01-12 14:45:20     Virat     Mumbai      Mobile  25000
2        103 2025-02-03 11:20:10     Dhoni    Chennai      Tablet  18000
3        104 2025-02-18 16:35:45     Rahul    Lucknow  Headphones   2500
4        105 2025-03-07 10:05:25    Hardik       Pune    Keyboard   1800
5        106 2025-03-25 18:50:40      Gill  Ahmedabad       Mouse    900
6        107 2025-04-10 08:30:15     Ishan    Kolkata     Monitor  15000
7        108 2025-04-22 13:40:55      Pant     Jaipur     Printer  12000
8        109 2025-05-05 17:10:35     Surya  Hyderabad      Camera  45000
9        110 2025-05-28 12:25:50    Bumrah      Delhi      Laptop  70000
10       111 2025-06-11 15:45:05  KL Rahul     Mumbai      Mobile  28000
11       112 2025-06-30 19:20:30    Jadeja    Chennai      Tablet  20000
12       113 2025-07-04 09:55:15    Ashwin    Lucknow    Keyboard   2200
13       114 2025-07-19 11:15:40     Shami       Pune       Mouse   1000
14       115 2025-08-08 14:05:25     Siraj  Ahmedabad     Monitor  17000
15       116 2025-08-26 16:50:10      Axar    Kolkata     Printer  14000
16       117 2025-09-09 10:40:20   Kuldeep  Hyderabad      Camera  48000
17       118 2025-10-14 18:30:45  Arshdeep     Jaipur      Laptop  72000
18       119 2025-11-21 13:15:35     Rinku      Delhi      Tablet  21000
19       120 2025-12-30 20:10:50     Tilak     Mumbai      Mobile  30000

In [6]:
print(df["Order_DateTime"].dt.year)

0     2025
1     2025
2     2025
3     2025
4     2025
5     2025
6     2025
7     2025
8     2025
9     2025
10    2025
11    2025
12    2025
13    2025
14    2025
15    2025
16    2025
17    2025
18    2025
19    2025
Name: Order_DateTime, dtype: int32

In [7]:
df["Order_DateTime"].dt.year

0     2025
1     2025
2     2025
3     2025
4     2025
5     2025
6     2025
7     2025
8     2025
9     2025
10    2025
11    2025
12    2025
13    2025
14    2025
15    2025
16    2025
17    2025
18    2025
19    2025
Name: Order_DateTime, dtype: int32

In [8]:
df["Order_DateTime"].dt.month

0      1
1      1
2      2
3      2
4      3
5      3
6      4
7      4
8      5
9      5
10     6
11     6
12     7
13     7
14     8
15     8
16     9
17    10
18    11
19    12
Name: Order_DateTime, dtype: int32

In [9]:
df["Order_DateTime"].dt.day

0      5
1     12
2      3
3     18
4      7
5     25
6     10
7     22
8      5
9     28
10    11
11    30
12     4
13    19
14     8
15    26
16     9
17    14
18    21
19    30
Name: Order_DateTime, dtype: int32

In [10]:
df["Order_DateTime"].dt.hour

0      9
1     14
2     11
3     16
4     10
5     18
6      8
7     13
8     17
9     12
10    15
11    19
12     9
13    11
14    14
15    16
16    10
17    18
18    13
19    20
Name: Order_DateTime, dtype: int32

In [11]:
df["Order_DateTime"].dt.minute

0     15
1     45
2     20
3     35
4      5
5     50
6     30
7     40
8     10
9     25
10    45
11    20
12    55
13    15
14     5
15    50
16    40
17    30
18    15
19    10
Name: Order_DateTime, dtype: int32

In [13]:
df["Order_DateTime"].dt.second

0     30
1     20
2     10
3     45
4     25
5     40
6     15
7     55
8     35
9     50
10     5
11    30
12    15
13    40
14    25
15    10
16    20
17    45
18    35
19    50
Name: Order_DateTime, dtype: int32

In [14]:
df["Order_DateTime"].dt.day_name()

0        Sunday
1        Sunday
2        Monday
3       Tuesday
4        Friday
5       Tuesday
6      Thursday
7       Tuesday
8        Monday
9     Wednesday
10    Wednesday
11       Monday
12       Friday
13     Saturday
14       Friday
15      Tuesday
16      Tuesday
17      Tuesday
18       Friday
19      Tuesday
Name: Order_DateTime, dtype: object

In [15]:
df["Order_DateTime"].dt.month_name()

0       January
1       January
2      February
3      February
4         March
5         March
6         April
7         April
8           May
9           May
10         June
11         June
12         July
13         July
14       August
15       August
16    September
17      October
18     November
19     December
Name: Order_DateTime, dtype: object

In [16]:
df["Order_DateTime"].dt.dayofweek

0     6
1     6
2     0
3     1
4     4
5     1
6     3
7     1
8     0
9     2
10    2
11    0
12    4
13    5
14    4
15    1
16    1
17    1
18    4
19    1
Name: Order_DateTime, dtype: int32

In [17]:
df["Order_DateTime"].dt.dayofyear

0       5
1      12
2      34
3      49
4      66
5      84
6     100
7     112
8     125
9     148
10    162
11    181
12    185
13    200
14    220
15    238
16    252
17    287
18    325
19    364
Name: Order_DateTime, dtype: int32

In [18]:
df["Order_DateTime"].dt.quarter

0     1
1     1
2     1
3     1
4     1
5     1
6     2
7     2
8     2
9     2
10    2
11    2
12    3
13    3
14    3
15    3
16    3
17    4
18    4
19    4
Name: Order_DateTime, dtype: int32

In [19]:
df["Order_DateTime"].dt.strftime("%d-%m-%Y")

0     05-01-2025
1     12-01-2025
2     03-02-2025
3     18-02-2025
4     07-03-2025
5     25-03-2025
6     10-04-2025
7     22-04-2025
8     05-05-2025
9     28-05-2025
10    11-06-2025
11    30-06-2025
12    04-07-2025
13    19-07-2025
14    08-08-2025
15    26-08-2025
16    09-09-2025
17    14-10-2025
18    21-11-2025
19    30-12-2025
Name: Order_DateTime, dtype: object

In [20]:
df["Order_DateTime"].dt.date

0     2025-01-05
1     2025-01-12
2     2025-02-03
3     2025-02-18
4     2025-03-07
5     2025-03-25
6     2025-04-10
7     2025-04-22
8     2025-05-05
9     2025-05-28
10    2025-06-11
11    2025-06-30
12    2025-07-04
13    2025-07-19
14    2025-08-08
15    2025-08-26
16    2025-09-09
17    2025-10-14
18    2025-11-21
19    2025-12-30
Name: Order_DateTime, dtype: object

In [21]:
df["Order_DateTime"].dt.time

0     09:15:30
1     14:45:20
2     11:20:10
3     16:35:45
4     10:05:25
5     18:50:40
6     08:30:15
7     13:40:55
8     17:10:35
9     12:25:50
10    15:45:05
11    19:20:30
12    09:55:15
13    11:15:40
14    14:05:25
15    16:50:10
16    10:40:20
17    18:30:45
18    13:15:35
19    20:10:50
Name: Order_DateTime, dtype: object

In [23]:
df["Order_DateTime"].dt.weekday

0     6
1     6
2     0
3     1
4     4
5     1
6     3
7     1
8     0
9     2
10    2
11    0
12    4
13    5
14    4
15    1
16    1
17    1
18    4
19    1
Name: Order_DateTime, dtype: int32

In [24]:
df["Order_DateTime"].dt.is_month_start

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: Order_DateTime, dtype: bool

In [25]:
df["Order_DateTime"].dt.is_month_end

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: Order_DateTime, dtype: bool

In [26]:
df["Order_DateTime"].dt.is_leap_year

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: Order_DateTime, dtype: bool

In [27]:
df["Order_DateTime"].dt.days_in_month

0     31
1     31
2     28
3     28
4     31
5     31
6     30
7     30
8     31
9     31
10    30
11    30
12    31
13    31
14    31
15    31
16    30
17    31
18    30
19    31
Name: Order_DateTime, dtype: int32

In [28]:
pd.Timestamp.now()

Timestamp('2026-07-02 10:12:19.182844')

In [29]:
pd.Timestamp.today()

Timestamp('2026-07-02 10:12:30.532482')

In [30]:
pd.Timedelta(days=5)

Timedelta('5 days 00:00:00')

In [34]:
print(df[df["Order_DateTime"].dt.dayofweek <6])
print("Total sales is: ", df[df["Order_DateTime"].dt.dayofweek <6] ["Sales"].sum())

    Order_ID      Order_DateTime  Customer       City     Product  Sales
2        103 2025-02-03 11:20:10     Dhoni    Chennai      Tablet  18000
3        104 2025-02-18 16:35:45     Rahul    Lucknow  Headphones   2500
4        105 2025-03-07 10:05:25    Hardik       Pune    Keyboard   1800
5        106 2025-03-25 18:50:40      Gill  Ahmedabad       Mouse    900
6        107 2025-04-10 08:30:15     Ishan    Kolkata     Monitor  15000
7        108 2025-04-22 13:40:55      Pant     Jaipur     Printer  12000
8        109 2025-05-05 17:10:35     Surya  Hyderabad      Camera  45000
9        110 2025-05-28 12:25:50    Bumrah      Delhi      Laptop  70000
10       111 2025-06-11 15:45:05  KL Rahul     Mumbai      Mobile  28000
11       112 2025-06-30 19:20:30    Jadeja    Chennai      Tablet  20000
12       113 2025-07-04 09:55:15    Ashwin    Lucknow    Keyboard   2200
13       114 2025-07-19 11:15:40     Shami       Pune       Mouse   1000
14       115 2025-08-08 14:05:25     Siraj  Ahmedabad     Monitor  17000
15       116 2025-08-26 16:50:10      Axar    Kolkata     Printer  14000
16       117 2025-09-09 10:40:20   Kuldeep  Hyderabad      Camera  48000
17       118 2025-10-14 18:30:45  Arshdeep     Jaipur      Laptop  72000
18       119 2025-11-21 13:15:35     Rinku      Delhi      Tablet  21000
19       120 2025-12-30 20:10:50     Tilak     Mumbai      Mobile  30000
Total sales is:  418400

### TASK

In [35]:
df

    Order_ID      Order_DateTime  Customer       City     Product  Sales
0        101 2025-01-05 09:15:30     Rohit      Delhi      Laptop  65000
1        102 2025-01-12 14:45:20     Virat     Mumbai      Mobile  25000
2        103 2025-02-03 11:20:10     Dhoni    Chennai      Tablet  18000
3        104 2025-02-18 16:35:45     Rahul    Lucknow  Headphones   2500
4        105 2025-03-07 10:05:25    Hardik       Pune    Keyboard   1800
5        106 2025-03-25 18:50:40      Gill  Ahmedabad       Mouse    900
6        107 2025-04-10 08:30:15     Ishan    Kolkata     Monitor  15000
7        108 2025-04-22 13:40:55      Pant     Jaipur     Printer  12000
8        109 2025-05-05 17:10:35     Surya  Hyderabad      Camera  45000
9        110 2025-05-28 12:25:50    Bumrah      Delhi      Laptop  70000
10       111 2025-06-11 15:45:05  KL Rahul     Mumbai      Mobile  28000
11       112 2025-06-30 19:20:30    Jadeja    Chennai      Tablet  20000
12       113 2025-07-04 09:55:15    Ashwin    Lucknow    Keyboard   2200
13       114 2025-07-19 11:15:40     Shami       Pune       Mouse   1000
14       115 2025-08-08 14:05:25     Siraj  Ahmedabad     Monitor  17000
15       116 2025-08-26 16:50:10      Axar    Kolkata     Printer  14000
16       117 2025-09-09 10:40:20   Kuldeep  Hyderabad      Camera  48000
17       118 2025-10-14 18:30:45  Arshdeep     Jaipur      Laptop  72000
18       119 2025-11-21 13:15:35     Rinku      Delhi      Tablet  21000
19       120 2025-12-30 20:10:50     Tilak     Mumbai      Mobile  30000

In [38]:
df["Year"] = df["Order_DateTime"].dt.year
print(df)

    Order_ID      Order_DateTime  Customer       City     Product  Sales  Year
0        101 2025-01-05 09:15:30     Rohit      Delhi      Laptop  65000  2025
1        102 2025-01-12 14:45:20     Virat     Mumbai      Mobile  25000  2025
2        103 2025-02-03 11:20:10     Dhoni    Chennai      Tablet  18000  2025
3        104 2025-02-18 16:35:45     Rahul    Lucknow  Headphones   2500  2025
4        105 2025-03-07 10:05:25    Hardik       Pune    Keyboard   1800  2025
5        106 2025-03-25 18:50:40      Gill  Ahmedabad       Mouse    900  2025
6        107 2025-04-10 08:30:15     Ishan    Kolkata     Monitor  15000  2025
7        108 2025-04-22 13:40:55      Pant     Jaipur     Printer  12000  2025
8        109 2025-05-05 17:10:35     Surya  Hyderabad      Camera  45000  2025
9        110 2025-05-28 12:25:50    Bumrah      Delhi      Laptop  70000  2025
10       111 2025-06-11 15:45:05  KL Rahul     Mumbai      Mobile  28000  2025
11       112 2025-06-30 19:20:30    Jadeja    Chennai      Tablet  20000  2025
12       113 2025-07-04 09:55:15    Ashwin    Lucknow    Keyboard   2200  2025
13       114 2025-07-19 11:15:40     Shami       Pune       Mouse   1000  2025
14       115 2025-08-08 14:05:25     Siraj  Ahmedabad     Monitor  17000  2025
15       116 2025-08-26 16:50:10      Axar    Kolkata     Printer  14000  2025
16       117 2025-09-09 10:40:20   Kuldeep  Hyderabad      Camera  48000  2025
17       118 2025-10-14 18:30:45  Arshdeep     Jaipur      Laptop  72000  2025
18       119 2025-11-21 13:15:35     Rinku      Delhi      Tablet  21000  2025
19       120 2025-12-30 20:10:50     Tilak     Mumbai      Mobile  30000  2025

In [42]:
df["Month_Name"] = df["Order_DateTime"].dt.month_name()
df

,Order_ID,Order_DateTime,Customer,City,Product,Sales,Year,Month_Name
0,101,2025-01-05 09:15:30,Rohit,Delhi,Laptop,65000,2025,January
1,102,2025-01-12 14:45:20,Virat,Mumbai,Mobile,25000,2025,January
2,103,2025-02-03 11:20:10,Dhoni,Chennai,Tablet,18000,2025,February
3,104,2025-02-18 16:35:45,Rahul,Lucknow,Headphones,2500,2025,February
4,105,2025-03-07 10:05:25,Hardik,Pune,Keyboard,1800,2025,March
5,106,2025-03-25 18:50:40,Gill,Ahmedabad,Mouse,900,2025,March
6,107,2025-04-10 08:30:15,Ishan,Kolkata,Monitor,15000,2025,April
7,108,2025-04-22 13:40:55,Pant,Jaipur,Printer,12000,2025,April
8,109,2025-05-05 17:10:35,Surya,Hyderabad,Camera,45000,2025,May
9,110,2025-05-28 12:25:50,Bumrah,Delhi,Laptop,70000,2025,May
10,111,2025-06-11 15:45:05,KL Rahul,Mumbai,Mobile,28000,2025,June
11,112,2025-06-30 19:20:30,Jadeja,Chennai,Tablet,20000,2025,June
12,113,2025-07-04 09:55:15,Ashwin,Lucknow,Keyboard,2200,2025,July
13,114,2025-07-19 11:15:40,Shami,Pune,Mouse,1000,2025,July
14,115,2025-08-08 14:05:25,Siraj,Ahmedabad,Monitor,17000,2025,August
15,116,2025-08-26 16:50:10,Axar,Kolkata,Printer,14000,2025,August
16,117,2025-09-09 10:40:20,Kuldeep,Hyderabad,Camera,48000,2025,September
17,118,2025-10-14 18:30:45,Arshdeep,Jaipur,Laptop,72000,2025,October
18,119,2025-11-21 13:15:35,Rinku,Delhi,Tablet,21000,2025,November
19,120,2025-12-30 20:10:50,Tilak,Mumbai,Mobile,30000,2025,December

In [46]:
df["Weekday"] = df["Order_DateTime"].dt.day_name()
df

,Order_ID,Order_DateTime,Customer,City,Product,Sales,Year,Month_Name,Weekday
0,101,2025-01-05 09:15:30,Rohit,Delhi,Laptop,65000,2025,January,Sunday
1,102,2025-01-12 14:45:20,Virat,Mumbai,Mobile,25000,2025,January,Sunday
2,103,2025-02-03 11:20:10,Dhoni,Chennai,Tablet,18000,2025,February,Monday
3,104,2025-02-18 16:35:45,Rahul,Lucknow,Headphones,2500,2025,February,Tuesday
4,105,2025-03-07 10:05:25,Hardik,Pune,Keyboard,1800,2025,March,Friday
5,106,2025-03-25 18:50:40,Gill,Ahmedabad,Mouse,900,2025,March,Tuesday
6,107,2025-04-10 08:30:15,Ishan,Kolkata,Monitor,15000,2025,April,Thursday
7,108,2025-04-22 13:40:55,Pant,Jaipur,Printer,12000,2025,April,Tuesday
8,109,2025-05-05 17:10:35,Surya,Hyderabad,Camera,45000,2025,May,Monday
9,110,2025-05-28 12:25:50,Bumrah,Delhi,Laptop,70000,2025,May,Wednesday
10,111,2025-06-11 15:45:05,KL Rahul,Mumbai,Mobile,28000,2025,June,Wednesday
11,112,2025-06-30 19:20:30,Jadeja,Chennai,Tablet,20000,2025,June,Monday
12,113,2025-07-04 09:55:15,Ashwin,Lucknow,Keyboard,2200,2025,July,Friday
13,114,2025-07-19 11:15:40,Shami,Pune,Mouse,1000,2025,July,Saturday
14,115,2025-08-08 14:05:25,Siraj,Ahmedabad,Monitor,17000,2025,August,Friday
15,116,2025-08-26 16:50:10,Axar,Kolkata,Printer,14000,2025,August,Tuesday
16,117,2025-09-09 10:40:20,Kuldeep,Hyderabad,Camera,48000,2025,September,Tuesday
17,118,2025-10-14 18:30:45,Arshdeep,Jaipur,Laptop,72000,2025,October,Tuesday
18,119,2025-11-21 13:15:35,Rinku,Delhi,Tablet,21000,2025,November,Friday
19,120,2025-12-30 20:10:50,Tilak,Mumbai,Mobile,30000,2025,December,Tuesday

In [50]:
print(df["Order_DateTime"].dt.quarter)

0     1
1     1
2     1
3     1
4     1
5     1
6     2
7     2
8     2
9     2
10    2
11    2
12    3
13    3
14    3
15    3
16    3
17    4
18    4
19    4
Name: Order_DateTime, dtype: int32

In [51]:
print(df["Order_DateTime"].dt.dayofyear)

0       5
1      12
2      34
3      49
4      66
5      84
6     100
7     112
8     125
9     148
10    162
11    181
12    185
13    200
14    220
15    238
16    252
17    287
18    325
19    364
Name: Order_DateTime, dtype: int32

In [53]:
print(df["Order_DateTime"].dt.dayofweek)

0     6
1     6
2     0
3     1
4     4
5     1
6     3
7     1
8     0
9     2
10    2
11    0
12    4
13    5
14    4
15    1
16    1
17    1
18    4
19    1
Name: Order_DateTime, dtype: int32

In [54]:
sales_df["Weekend"] = sales_df["Order_DateTime"].dt.dayofweek >= 5
print(sales_df)

    Order_ID      Order_DateTime  Customer       City     Product  Sales  \
0        101 2025-01-05 09:15:30     Rohit      Delhi      Laptop  65000
1        102 2025-01-12 14:45:20     Virat     Mumbai      Mobile  25000
2        103 2025-02-03 11:20:10     Dhoni    Chennai      Tablet  18000
3        104 2025-02-18 16:35:45     Rahul    Lucknow  Headphones   2500
4        105 2025-03-07 10:05:25    Hardik       Pune    Keyboard   1800
5        106 2025-03-25 18:50:40      Gill  Ahmedabad       Mouse    900
6        107 2025-04-10 08:30:15     Ishan    Kolkata     Monitor  15000
7        108 2025-04-22 13:40:55      Pant     Jaipur     Printer  12000
8        109 2025-05-05 17:10:35     Surya  Hyderabad      Camera  45000
9        110 2025-05-28 12:25:50    Bumrah      Delhi      Laptop  70000
10       111 2025-06-11 15:45:05  KL Rahul     Mumbai      Mobile  28000
11       112 2025-06-30 19:20:30    Jadeja    Chennai      Tablet  20000
12       113 2025-07-04 09:55:15    Ashwin    Lucknow    Keyboard   2200
13       114 2025-07-19 11:15:40     Shami       Pune       Mouse   1000
14       115 2025-08-08 14:05:25     Siraj  Ahmedabad     Monitor  17000
15       116 2025-08-26 16:50:10      Axar    Kolkata     Printer  14000
16       117 2025-09-09 10:40:20   Kuldeep  Hyderabad      Camera  48000
17       118 2025-10-14 18:30:45  Arshdeep     Jaipur      Laptop  72000
18       119 2025-11-21 13:15:35     Rinku      Delhi      Tablet  21000
19       120 2025-12-30 20:10:50     Tilak     Mumbai      Mobile  30000

    Weekend
0      True
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13     True
14    False
15    False
16    False
17    False
18    False
19    False

In [58]:
print(df["Order_DateTime"].dt.strftime("%d-%m-%Y"))

0     05-01-2025
1     12-01-2025
2     03-02-2025
3     18-02-2025
4     07-03-2025
5     25-03-2025
6     10-04-2025
7     22-04-2025
8     05-05-2025
9     28-05-2025
10    11-06-2025
11    30-06-2025
12    04-07-2025
13    19-07-2025
14    08-08-2025
15    26-08-2025
16    09-09-2025
17    14-10-2025
18    21-11-2025
19    30-12-2025
Name: Order_DateTime, dtype: object

In [61]:
print(df["Order_DateTime"].dt.strftime("%B %d, %Y"))

0       January 05, 2025
1       January 12, 2025
2      February 03, 2025
3      February 18, 2025
4         March 07, 2025
5         March 25, 2025
6         April 10, 2025
7         April 22, 2025
8           May 05, 2025
9           May 28, 2025
10         June 11, 2025
11         June 30, 2025
12         July 04, 2025
13         July 19, 2025
14       August 08, 2025
15       August 26, 2025
16    September 09, 2025
17      October 14, 2025
18     November 21, 2025
19     December 30, 2025
Name: Order_DateTime, dtype: object

In [62]:
print(df["Order_DateTime"].dt.strftime("%d/%m/%Y %I:%M %p"))

0     05/01/2025 09:15 AM
1     12/01/2025 02:45 PM
2     03/02/2025 11:20 AM
3     18/02/2025 04:35 PM
4     07/03/2025 10:05 AM
5     25/03/2025 06:50 PM
6     10/04/2025 08:30 AM
7     22/04/2025 01:40 PM
8     05/05/2025 05:10 PM
9     28/05/2025 12:25 PM
10    11/06/2025 03:45 PM
11    30/06/2025 07:20 PM
12    04/07/2025 09:55 AM
13    19/07/2025 11:15 AM
14    08/08/2025 02:05 PM
15    26/08/2025 04:50 PM
16    09/09/2025 10:40 AM
17    14/10/2025 06:30 PM
18    21/11/2025 01:15 PM
19    30/12/2025 08:10 PM
Name: Order_DateTime, dtype: object

In [64]:
print(df[df["Order_DateTime"] > "2025-06-30"])

    Order_ID      Order_DateTime  Customer       City   Product  Sales  Year  \
11       112 2025-06-30 19:20:30    Jadeja    Chennai    Tablet  20000  2025
12       113 2025-07-04 09:55:15    Ashwin    Lucknow  Keyboard   2200  2025
13       114 2025-07-19 11:15:40     Shami       Pune     Mouse   1000  2025
14       115 2025-08-08 14:05:25     Siraj  Ahmedabad   Monitor  17000  2025
15       116 2025-08-26 16:50:10      Axar    Kolkata   Printer  14000  2025
16       117 2025-09-09 10:40:20   Kuldeep  Hyderabad    Camera  48000  2025
17       118 2025-10-14 18:30:45  Arshdeep     Jaipur    Laptop  72000  2025
18       119 2025-11-21 13:15:35     Rinku      Delhi    Tablet  21000  2025
19       120 2025-12-30 20:10:50     Tilak     Mumbai    Mobile  30000  2025

   Month_Name   Weekday
11       June    Monday
12       July    Friday
13       July  Saturday
14     August    Friday
15     August   Tuesday
16  September   Tuesday
17    October   Tuesday
18   November    Friday
19   December   Tuesday

In [66]:
print(df[df["Order_DateTime"].dt.month == 7])

    Order_ID      Order_DateTime Customer     City   Product  Sales  Year  \
12       113 2025-07-04 09:55:15   Ashwin  Lucknow  Keyboard   2200  2025
13       114 2025-07-19 11:15:40    Shami     Pune     Mouse   1000  2025

   Month_Name   Weekday
12       July    Friday
13       July  Saturday

In [69]:
print(df[df["Order_DateTime"].dt.year == 2025])

    Order_ID      Order_DateTime  Customer       City     Product  Sales  \
0        101 2025-01-05 09:15:30     Rohit      Delhi      Laptop  65000
1        102 2025-01-12 14:45:20     Virat     Mumbai      Mobile  25000
2        103 2025-02-03 11:20:10     Dhoni    Chennai      Tablet  18000
3        104 2025-02-18 16:35:45     Rahul    Lucknow  Headphones   2500
4        105 2025-03-07 10:05:25    Hardik       Pune    Keyboard   1800
5        106 2025-03-25 18:50:40      Gill  Ahmedabad       Mouse    900
6        107 2025-04-10 08:30:15     Ishan    Kolkata     Monitor  15000
7        108 2025-04-22 13:40:55      Pant     Jaipur     Printer  12000
8        109 2025-05-05 17:10:35     Surya  Hyderabad      Camera  45000
9        110 2025-05-28 12:25:50    Bumrah      Delhi      Laptop  70000
10       111 2025-06-11 15:45:05  KL Rahul     Mumbai      Mobile  28000
11       112 2025-06-30 19:20:30    Jadeja    Chennai      Tablet  20000
12       113 2025-07-04 09:55:15    Ashwin    Lucknow    Keyboard   2200
13       114 2025-07-19 11:15:40     Shami       Pune       Mouse   1000
14       115 2025-08-08 14:05:25     Siraj  Ahmedabad     Monitor  17000
15       116 2025-08-26 16:50:10      Axar    Kolkata     Printer  14000
16       117 2025-09-09 10:40:20   Kuldeep  Hyderabad      Camera  48000
17       118 2025-10-14 18:30:45  Arshdeep     Jaipur      Laptop  72000
18       119 2025-11-21 13:15:35     Rinku      Delhi      Tablet  21000
19       120 2025-12-30 20:10:50     Tilak     Mumbai      Mobile  30000

    Year Month_Name    Weekday
0   2025    January     Sunday
1   2025    January     Sunday
2   2025   February     Monday
3   2025   February    Tuesday
4   2025      March     Friday
5   2025      March    Tuesday
6   2025      April   Thursday
7   2025      April    Tuesday
8   2025        May     Monday
9   2025        May  Wednesday
10  2025       June  Wednesday
11  2025       June     Monday
12  2025       July     Friday
13  2025       July   Saturday
14  2025     August     Friday
15  2025     August    Tuesday
16  2025  September    Tuesday
17  2025    October    Tuesday
18  2025   November     Friday
19  2025   December    Tuesday

In [70]:
print(sales_df[sales_df["Order_DateTime"].dt.hour >= 15])

    Order_ID      Order_DateTime  Customer       City     Product  Sales  \
3        104 2025-02-18 16:35:45     Rahul    Lucknow  Headphones   2500
5        106 2025-03-25 18:50:40      Gill  Ahmedabad       Mouse    900
8        109 2025-05-05 17:10:35     Surya  Hyderabad      Camera  45000
10       111 2025-06-11 15:45:05  KL Rahul     Mumbai      Mobile  28000
11       112 2025-06-30 19:20:30    Jadeja    Chennai      Tablet  20000
15       116 2025-08-26 16:50:10      Axar    Kolkata     Printer  14000
17       118 2025-10-14 18:30:45  Arshdeep     Jaipur      Laptop  72000
19       120 2025-12-30 20:10:50     Tilak     Mumbai      Mobile  30000

    Weekend
3     False
5     False
8     False
10    False
11    False
15    False
17    False
19    False

In [74]:
print(sales_df[sales_df["Order_DateTime"].dt.day_name() == "Saturday"])

    Order_ID      Order_DateTime Customer  City Product  Sales  Weekend
13       114 2025-07-19 11:15:40    Shami  Pune   Mouse   1000     True